version: '3.8'

services:
  diamond-nursery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diamond-nursery-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3080:3000"
    volumes:
      - ./app/data:/app/app/data
      - ./public/diamondnursery:/app/public/diamondnursery
    env_file:
      - .env.local
